spec_version: 2 

environment:
  environment_name: params-shell
  state: active
  owner_email: johnathan.v@quali.com
  spaces:
  - Vido

inputs:
  agent:
    type: agent

grains:
  shell:
    kind: blueprint
    spec:
      source:
        store: bps
        path: blueprints/shell-print-params.yaml
      inputs:
      - agent: '{{ .inputs.agent }}'
