spec_version: 2
description: Workflow to power on Azure VMs via built-in action

inputs:
  version:
    pattern: '^[a-zA-Z0-9.-]+$'
    validation-description: "The provided value must contain only letters, numbers, dots, and hyphens"
    allowed-values:
      - 'v1.2.3'
      - 'develop-v2' 
      - 'develop'
  blueprint_template:
    pattern: '^[a-zA-Z0-9-]+$'
    validation-description: "The provided value must contain only letters, numbers, and hyphens"
    allowed-values:
      - 'EnvType_v2'
  template_folder:
    pattern: '^[a-zA-Z0-9-]+$'
    validation-description: "The provided value must contain only letters, numbers, and hyphens"
    allowed-values:
      - 'DevOps'
  store:
    pattern: '^[a-zA-Z0-9-]+$'
    validation-description: "The provided value must contain only letters, numbers, and hyphens"
    allowed-values:
      - 'tf-envs-metadata-granularity'
  repository:
    pattern: '^[a-zA-Z0-9-]+$'
    validation-description: "The provided value must contain only letters, numbers, and hyphens"
    allowed-values:
      - 'tf-envs-metadata' 

workflow:
  scope: space
  labels-selector: Azure-VM

grains:
  setup:
    kind: shell
    spec: 
      agent:
        name: 'vido-vido-prod'
      activities:
        deploy:
          commands:
            - "echo setup script is running..."
        destroy:
          commands:
            - "echo destroy activity..."
