spec_version: 2

inputs:
  agent:
    type: agent
    
grains:
  common:
    kind: aws-cdk
    spec:
      source:
        store: bps
        path: cdk/python/s3-config
      agent:
        name: '{{ .inputs.agent }}'
      env-vars:
        - CDK_CONFIG_FILE: '$CONFIG_REPO_PATH/vido'
      workspace-directories:
        - source:
            store: config-repo
            name: CONFIG_REPO_PATH
